# Generated by Django 4.2.6 on 2023-10-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('empaddress', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('salary', models.BigIntegerField()),
            ],
        ),
    ]
